# redriver/features.py

import pandas as pd
from pathlib import Path
from redriver.config import (
    RAW_FLOWS_PATH,
    FEATURES_PATH,
    LABEL_COLUMN,
)

# ---------------------------------------------------------
# Load synthetic flows
# ---------------------------------------------------------

def load_flows(path: Path) -> pd.DataFrame:
    print(f"[RedRiver] Loading raw flows from: {path}")
    return pd.read_csv(path)


# ---------------------------------------------------------
# Feature engineering
# ---------------------------------------------------------

def compute_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create ML-ready features from the RedRiver flow dataset.
    Matches the REAL column names generated by synthetic.py
    """

    print("[RedRiver] Computing derived features...")

    # --- Basic numeric features already exist ---
    # duration, bytes_sent, bytes_received, packets
    # You also have ports & protocol.

    # One-hot encode protocol
    df = pd.get_dummies(df, columns=["protocol"], prefix="proto")

    # Add throughput features
    df["kb_sent"] = df["bytes_sent"] / 1024
    df["kb_received"] = df["bytes_received"] / 1024
    df["bytes_total"] = df["bytes_sent"] + df["bytes_received"]

    # Flows-per-second estimate
    df["rate_packets"] = df["packets"] / (df["duration"] + 0.1)
    df["rate_bytes"] = df["bytes_total"] / (df["duration"] + 0.1)

    # Ports as binary features (privileged vs high)
    df["src_port_privileged"] = (df["src_port"] < 1024).astype(int)
    df["dst_port_privileged"] = (df["dst_port"] < 1024).astype(int)

    # Drop non-numeric / IP fields
    df = df.drop(columns=["src_ip", "dst_ip"])

    print(f"[RedRiver] Feature matrix shape: {df.shape}")
    return df


# ---------------------------------------------------------
# Save features
# ---------------------------------------------------------

def save_features(df: pd.DataFrame, path: Path) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    print(f"[RedRiver] Saved features to: {path}")
    return str(path)


# ---------------------------------------------------------
# Combined pipeline
# ---------------------------------------------------------

def run_feature_pipeline() -> None:
    print("[RedRiver] ===== Starting Feature Pipeline =====")

    df = load_flows(RAW_FLOWS_PATH)

    feats = compute_features(df)

    FEATURE_PATH = save_features(feats, FEATURES_PATH)

    print("[RedRiver] Feature pipeline complete.")
    print("[RedRiver] Output:", FEATURE_PATH)


if __name__ == "__main__":
    run_feature_pipeline()
